export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED"

export const PUT_PROFILE_REQUEST = "PUT_PROFILE_REQUEST"
export const PUT_PROFILE_SUCCESS = "PUT_PROFILE_SUCCESS"
export const PUT_PROFILE_FAILED = "PUT_PROFILE_FAILED"

export const PUT_ROLE_REQUEST = "PUT_ROLE_REQUEST"
export const PUT_ROLE_SUCCESS = "PUT_ROLE_SUCCESS"
export const PUT_ROLE_FAILED = "PUT_ROLE_FAILED"

export const LOGOUT = "LOGOUT"