export const ADD_TRIP_REQUEST = "ADD_TRIP_REQUEST";
export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS ";
export const ADD_TRIP_FAILED = "ADD_TRIP_FAILED";

export const GET_TRIP_REQUEST = "GET_TRIP_REQUEST";
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS";
export const GET_TRIP_FAILED = "GET_TRIP_FAILED";

export const GET_TRIP_COUNT_REQUEST = "GET_TRIP_COUNT_REQUEST";
export const GET_TRIP_COUNT_SUCCESS = "GET_TRIP_COUNT_SUCCESS";
export const GET_TRIP_COUNT_FAILED = "GET_TRIP_COUNT_FAILED";

export const GET_ALL_TRIP_REQUEST = "GET_ALL_TRIP_REQUEST";
export const GET_ALL_TRIP_SUCCESS = "GET_ALL_TRIP_SUCCESS";
export const GET_ALL_TRIP_FAILED = "GET_ALL_TRIP_FAILED";

export const FIND_TRIPS_REQUEST = "FIND_TRIPS_REQUEST";
export const FIND_TRIPS_SUCCESS = "FIND_TRIPS_SUCCESS";
export const FIND_TRIPS_FAILED = "FIND_TRIPS_FAILED";

export const GET_SELECTED_TRIP_REQUEST = "GET_SELECTED_TRIP_REQUEST";
export const GET_SELECTED_TRIP_SUCCESS = "GET_SELECTED_TRIP_SUCCESS";
export const GET_SELECTED_TRIP_FAILED = "GET_SELECTED_TRIP_FAILED";
export const GET_RESERVED_TRIP_REQUEST = "GET_RESERVED_TRIP_REQUEST";
export const GET_RESERVED_TRIP_SUCCESS = "GET_RESERVED_TRIP_SUCCESS";
export const GET_RESERVED_TRIP_FAILED = "GET_RESERVED_TRIP_FAILED";

export const PUT_SEATING_CAPACITY_REQUEST = "PUT_SEATING_CAPACITY_REQUEST";
export const PUT_SEATING_CAPACITY_SUCCESS = "PUT_SEATING_CAPACITY_SUCCESS";
export const PUT_SEATING_CAPACITY_FAILED = "PUT_SEATING_CAPACITY_FAILED";

export const PUT_TRIP_REQUEST = "PUT_TRIP_REQUEST";
export const PUT_TRIP_SUCCESS = "PUT_TRIP_SUCCESS";
export const PUT_TRIP_FAILED = "PUT_TRIP_FAILED";

export const DELETE_TRIP_REQUEST = "DELETE_TRIP_REQUEST";
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_FAILED = "DELETE_TRIP_FAILED";
